subprojects {
    apply plugin: "java"

    group "lol.pyr"
    version "2.1.0" + (System.getenv().containsKey("BUILD_ID") ? "-SNAPSHOT" : "")

    java {
        toolchain.languageVersion.set(JavaLanguageVersion.of(21))
    }

    dependencies {
        compileOnly "org.jetbrains:annotations:26.0.1"
        compileOnly "org.spigotmc:spigot-api:1.8.8-R0.1-SNAPSHOT"
    }

    repositories {
        mavenCentral()
        maven {
            url "https://hub.spigotmc.org/nexus/content/repositories/snapshots/"
        }
        maven {
            url "https://repo.codemc.io/repository/maven-releases/"
        }
        maven {
            url "https://libraries.minecraft.net"
        }
        maven {
            url "https://repo.papermc.io/repository/maven-public/"
        }
        maven {
            url "https://repo.extendedclip.com/content/repositories/placeholderapi/"
        }
        maven {
            url "https://repo.pyr.lol/releases"
        }
    }
}
