plugins {
    id "java"
    id "maven-publish"
}

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = "znpcsplus-api"

            pom {
                name.set("znpcsplus-api")
                description.set("The API for the ZNPCsPlus plugin")
                url.set("https://github.com/Pyrbu/ZNPCsPlus")
            }
        }
    }
    repositories {
        maven {
            Map<String, String> systemProperties = System.getenv()
            credentials {
                if (systemProperties.containsKey("MAVEN_USERNAME")) username systemProperties.get("MAVEN_USERNAME")
                else if (systemProperties.containsKey("DIST_USERNAME")) username systemProperties.get("DIST_USERNAME")
                if (systemProperties.containsKey("MAVEN_PASSWORD")) password systemProperties.get("MAVEN_PASSWORD")
                else if (systemProperties.containsKey("DIST_PASSWORD")) password systemProperties.get("DIST_PASSWORD")
            }
            url = uri("https://repo.turkishpvp.llc/public-repo")
        }
    }
}
